name: Deploy Database package to TestPyPI

on:
  workflow_dispatch:
    inputs:
      version_input:
        description: 'Version number to be deployed'
        required: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/nmbrs_database/requirements.txt
          pip install --upgrade build twine

      - name: Increase version number
        run:  python set_version.py --version=${{ github.event.inputs.version_input }} --path=src/nmbrs_database

      - name: Build package
        run: python -m build

      - name: Deploy to TestPyPI
        run: python -m twine upload --repository testpypi -p ${{ secrets.TEST_PYPI_PASSWORD }} -u ${{ secrets.TEST_PYPI_USERNAME }} dist/*
