name: Deploy to TestPyPI

on:
  push:
    branches:
      - main
      - 13-setup-deployment-in-cicd # the branch this feature was added in

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade build twine

      - name: Increase version number
        run: |
          ls
          python increase_version.py

      - name: Build package
        run: |
          python -m build

      - name: Deploy to TestPyPI
        run: |
          python -m twine upload --repository testpypi -p ${{ secrets.TEST_PYPI_PASSWORD }} -u ${{ secrets.TEST_PYPI_USERNAME }} dist/*
